### PR TITLE
Summer 2020 Updates

### PR DESCRIPTION
**Pull request by Daehoon7992**
ui.r and server.
1. Improved code readability by adding space after comma and symbols(<-, =, and <<-)

ui.r
2. Changed the prerequisite paragraph on correlation and regression(by myself for this paragraph)

3. Took out tags$strong from textOutput("question")

4. Removed the space on the reference line

** Note that this app has two Github folder. This one should be the most recent one and the one should be used.

### CODE REVIEW

**Review by NurulSyafiqah-pixel — CHANGES_REQUESTED** [review]
1) The app runs with so many warnings.
2) The README file is incomplete: there is no badge. (in dev branch)
3) There is no DESCRIPTION file.  (also received warning on this)

Recommended Priority: Medium

**Review by robchapp — CHANGES_REQUESTED** [review]
This app runs well but I think it needs some changes. The game/activity needs better explained, it is somewhat vague what the app is trying to show. Other issues include not having a feedback button. The info button is just a copy of the instructions on the overview, and not having a citation on the overview. The button on the overview to the prereqs does not have the prereqs icon, and an undescriptive name.

**Review by tarynmch — CHANGES_REQUESTED** [review]
I noticed the same things as the last peer review. Both buttons are the wrong icon and undescriptive, missing the citation at bottom of overview, no feedback icon, and the i icon should be different then the overview instructions. I also agree that the explore page is a bit vague and there could be more of a description at the top and the feedback could include hints on how to complete the task. The code is also not camelCase when needed, like, "newchallenge." Badges are missing from README file. Then some other files are missing like description, todo, docs, and others to be up to date with BOAST.

**Review by tarynmch — CHANGES_REQUESTED** [review]
Good work with updating it. The only things I noticed was that there is no ggplot2 reference and no alt text for the graph.

**Comment by Sburke26** [comment]
Thank you for reviewing.
I fixed the issues with the reference page and the alt text.
Please let me know if there is anything else you notice.

**Review by tarynmch — CHANGES_REQUESTED** [review]
Looks great, just make sure that the description in the README file mentions correlation like the other descriptions do.

**Pull request merged**
